### PR TITLE
squidpy v1.4.1

### PR DESCRIPTION
**Pull request by giovp**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by michalk8 — COMMENTED** [review]
Seems like there's an issue installing `spatialdata`, because `spatial_image==0.3.0` is pinned:
package spatialdata-0.0.15-pyhd8ed1ab_0 requires spatial-image <=0.3.0, but none of the providers can be installed

**Comment by giovp** [comment]
ah yeah, I think this will take time to unpin...

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
Working on a fix here: https://github.com/conda-forge/squidpy-feedstock/pulls
I have also fixed dependencies of this package.

@giovp please be aware that you should not create a branch in this repo. All branches are pushed to anaconda. A PR should always come from external repos.

**Comment by bgruening** [comment]
superseded by https://github.com/conda-forge/squidpy-feedstock/pull/8

**Pull request closed without merging**
